#ifndef TEMPLATELIB_GLOBAL_H
#define TEMPLATELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPLATELIB_LIBRARY)
#define TEMPLATELIB_EXPORT Q_DECL_EXPORT
#else
#define TEMPLATELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPLATELIB_GLOBAL_H
